"""initial migration

Revision ID: 1214effb3fe4
Revises: None
Create Date: 2016-01-13 21:38:01.757848

"""

# revision identifiers, used by Alembic.
revision = '1214effb3fe4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
