"""add private column into db article

Revision ID: 1d86eda8c12f
Revises: 1214effb3fe4
Create Date: 2016-01-13 21:50:39.164949

"""

# revision identifiers, used by Alembic.
revision = '1d86eda8c12f'
down_revision = '1214effb3fe4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('private', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'private')
    ### end Alembic commands ###
