"""add tags field to articles table

Revision ID: 1f800803b6f5
Revises: 5a6b7c5aede7
Create Date: 2016-01-23 18:37:52.521942

"""

# revision identifiers, used by Alembic.
revision = '1f800803b6f5'
down_revision = '5a6b7c5aede7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
