"""add Image model for image file management

Revision ID: 230a043fde77
Revises: 4d5f608b8d34
Create Date: 2016-03-12 13:43:34.858864

"""

# revision identifiers, used by Alembic.
revision = '230a043fde77'
down_revision = '4d5f608b8d34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
