"""Article markdown support

Revision ID: 4d5f608b8d34
Revises: 1f800803b6f5
Create Date: 2016-02-12 16:40:46.587342

"""

# revision identifiers, used by Alembic.
revision = '4d5f608b8d34'
down_revision = '1f800803b6f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content_html', sa.UnicodeText(), nullable=True))
    op.add_column('articles', sa.Column('content_pre', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'content_pre')
    op.drop_column('articles', 'content_html')
    ### end Alembic commands ###
