"""add new tables categories and series, and foreign key in articles table

Revision ID: 5a6b7c5aede7
Revises: 1d86eda8c12f
Create Date: 2016-01-19 21:28:34.100699

"""

# revision identifiers, used by Alembic.
revision = '5a6b7c5aede7'
down_revision = '1d86eda8c12f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('series_id', sa.Integer(), nullable=True))
    op.alter_column('articles', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('articles', 'time_created',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('articles', 'time_modified',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('articles', 'time_modified',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('articles', 'time_created',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('articles', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('articles', 'series_id')
    op.drop_column('articles', 'category_id')
    ### end Alembic commands ###
